### ISSUE TITLE
Missing EventEmitter API

### ISSUE THREAD

**Issue by ibc** [Morglod/ts-event-emitter#2]
For instance, the "newListener" event is not implemented. There are others.

Just wondering: is it really posible that those [90 lines](https://github.com/Morglod/tsee/blob/master/src/ee.ts) do the same as those [647 lines](https://github.com/nodejs/node/blob/master/lib/events.js)?

**Comment by Morglod** [comment]
tsee has simple implementation for simple usage. If you really want all features, you should use  `asTypedEventEmitter` function or just type casting.
I never saw advanced usage of EventEmitters, simple implementation is enough almost everywhere.

Also there is no tests currently in tsee.

What project your working on, than you need `newListener` event? 😮

**Comment by ibc** [comment]
The thing is that I cannot use `asTypedEventEmitter()` into [my class definition](https://github.com/Morglod/tsee/issues/1#issuecomment-564036231).

I'm not using `newListener` in any project right now, but I needed it in the past.
